# Generated by Django 4.1.5 on 2023-01-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[(1, "SYADMIN"), (2, "Designer"), (3, "Customer")],
                default=1,
                max_length=10,
            ),
        ),
    ]
