# Generated by Django 4.0.6 on 2022-09-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryoptions',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': 'The price must be between 0 and 99999999999999.99.'}}, help_text='Maximum 99999999999999.99', max_digits=14, verbose_name='delivery price'),
        ),
    ]
